package config

import (
	"fmt"
	"strings"
)

// GenerateAnnotatedConfig renders a complete, commented srepd configuration
// with every supported key at its default value — for users who prefer
// reading and editing a file over the interactive wizard (#324). Required
// keys are emitted empty so a generated file routes into the wizard (OB-1)
// instead of failing PagerDuty auth with a placeholder. The dead flag_marker
// key (issue #322) is deliberately absent.
func GenerateAnnotatedConfig() []byte {
	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString("# SREPD configuration — ~/.config/srepd/srepd.yaml\n")
	sb.WriteString("# Generated by `srepd config generate`.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Prefer the interactive wizard: run `srepd config`. It validates your\n")
	sb.WriteString("# token and discovers teams and escalation policies for you.\n")

	sb.WriteString("\n# --- Required ---\n\n")
	sb.WriteString("# PagerDuty API token.\n")
	sb.WriteString("# Create one at: PagerDuty web → My Profile → User Settings →\n")
	sb.WriteString("# API Access → Create New API User Token.\n")
	sb.WriteString("token: \"\"\n")
	sb.WriteString("\n# PagerDuty team IDs to monitor. Tip: most users need exactly one team.\n")
	sb.WriteString("# The wizard discovers these from your token.\n")
	sb.WriteString("teams: []\n")

	sb.WriteString("\n# --- Environment ---\n\n")
	for _, entry := range []struct{ key, comment string }{
		{"editor", "Editor for incident notes."},
		{"terminal", "Terminal emulator for cluster login. Set only the name; the\n# argument style is detected automatically."},
		{"cluster_login_command", "Command run to log into a cluster. %%CLUSTER_ID%% and\n# %%INCIDENT_ID%% are substituted at launch."},
		{"toolbox_mode", "Fedora Toolbox detection: auto, true, or false."},
		{"chord_prefix", "Prefix key for chord commands."},
		{"rosa_boundary_command", "rosa-boundary cluster login command."},
	} {
		fmt.Fprintf(&sb, "# %s\n%s: %s\n\n", entry.comment, entry.key, DefaultOptionalKeys[entry.key])
	}

	sb.WriteString("# --- Behavior ---\n\n")
	sb.WriteString("# Use emoji markers for flags/agent/watcher (false = text fallbacks).\n")
	sb.WriteString("emoji: true\n\n")
	sb.WriteString("# Escalation level ctrl+e re-escalates to, skipping placeholder tiers.\n")
	sb.WriteString("reescalate_level: 2\n\n")
	sb.WriteString("# Stream :watcher/LLM responses token-by-token when supported.\n")
	sb.WriteString("stream_responses: true\n")

	sb.WriteString("\n# --- Escalation policies (optional — the wizard discovers these) ---\n\n")
	sb.WriteString("# Policy incidents are reassigned to when silenced; use one that routes\n")
	sb.WriteString("# only to bot users, never on-call humans.\n")
	sb.WriteString("# default_silent_escalation_policy: \"PXXXXXX\"\n\n")
	sb.WriteString("# Per-service overrides when a service needs a different silent policy.\n")
	sb.WriteString("# custom_service_escalation_policies:\n")
	sb.WriteString("#   SERVICE_ID: POLICY_ID\n")

	sb.WriteString("\n# --- AI features (optional) ---\n\n")
	sb.WriteString("# CLI agent for :agent queries. Empty string disables AI features.\n")
	fmt.Fprintf(&sb, "# agent_cli_command: %s\n\n", DefaultOptionalKeys["agent_cli_command"])
	sb.WriteString("# Custom system prompts for :agent and the ambient watcher.\n")
	sb.WriteString("# agent_system_prompt: \"\"\n")
	sb.WriteString("# watcher_system_prompt: \"\"\n\n")
	sb.WriteString("# LLM API provider for the :watcher (see docs/ai-agents.md).\n")
	sb.WriteString("# llm_api:\n")
	sb.WriteString("#   provider: \"\"\n")
	sb.WriteString("#   api_key_env: \"\"\n")
	sb.WriteString("#   model: \"\"\n")
	sb.WriteString("#   endpoint: \"\"\n")

	sb.WriteString("\n# --- Colors (optional, hex values; see docs/colors.md) ---\n\n")
	sb.WriteString("# colors:\n")
	sb.WriteString("#   text: \"#778da9\"\n")
	sb.WriteString("#   border: \"#415a77\"\n")
	sb.WriteString("#   highlight: \"#ffffff\"\n")
	sb.WriteString("#   selected: \"#415a77\"\n")
	sb.WriteString("#   warning: \"#a4133c\"\n")
	sb.WriteString("#   error: \"#0d1b2a\"\n")
	sb.WriteString("#   muted: \"#5C5C5C\"\n")

	return []byte(sb.String())
}
