package config

import (
	"fmt"
	"strings"
)

// GenerateEnvironment holds auto-detected environment values for config
// generation. Each field is a ranked list: the first entry becomes the
// active value, the rest are written as commented-out alternatives.
type GenerateEnvironment struct {
	Terminals        []string // detected terminal commands, best first
	Editor           string   // resolved from $EDITOR/$VISUAL/vim
	AgentCLI         string   // "claude --print" when claude is on PATH, else ""
	ClusterLoginCmds []string // detected cluster login commands, best first
}

// GenerateAnnotatedConfig renders a complete, commented srepd configuration.
// When env is non-nil, detected values replace the static defaults and
// alternatives are listed as comments. Required keys are emitted empty so a
// generated file routes into the wizard (OB-1).
func GenerateAnnotatedConfig(env *GenerateEnvironment) []byte {
	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString("# SREPD configuration — ~/.config/srepd/srepd.yaml\n")
	sb.WriteString("# Generated by `srepd config generate`.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Prefer the interactive wizard: run `srepd config`. It validates your\n")
	sb.WriteString("# token and discovers teams and escalation policies for you.\n")

	sb.WriteString("\n# --- Required ---\n\n")
	sb.WriteString("# PagerDuty API token.\n")
	sb.WriteString("# Create one at: PagerDuty web → My Profile → User Settings →\n")
	sb.WriteString("# API Access → Create New API User Token.\n")
	sb.WriteString("token: \"\"\n")
	sb.WriteString("\n# PagerDuty team IDs to monitor. Tip: most users need exactly one team.\n")
	sb.WriteString("# The wizard discovers these from your token.\n")
	sb.WriteString("teams: []\n")

	sb.WriteString("\n# --- Environment ---\n\n")

	// Editor — use detected value or fall back to default.
	editor := DefaultOptionalKeys["editor"]
	if env != nil && env.Editor != "" {
		editor = env.Editor
	}
	fmt.Fprintf(&sb, "# Editor for incident notes.\neditor: %s\n\n", editor)

	// Terminal — use first detected terminal, list the rest as comments.
	terminal := DefaultOptionalKeys["terminal"]
	if env != nil && len(env.Terminals) > 0 {
		terminal = env.Terminals[0]
	}
	sb.WriteString("# Terminal emulator for cluster login. Set only the name; the\n")
	sb.WriteString("# argument style is detected automatically.\n")
	fmt.Fprintf(&sb, "terminal: %s\n", terminal)
	if env != nil && len(env.Terminals) > 1 {
		sb.WriteString("# Also detected on this system:\n")
		for _, alt := range env.Terminals[1:] {
			fmt.Fprintf(&sb, "# terminal: %s\n", alt)
		}
	}
	sb.WriteString("\n")

	// Cluster login command — use first detected, list the rest as comments.
	clusterLogin := DefaultOptionalKeys["cluster_login_command"]
	if env != nil && len(env.ClusterLoginCmds) > 0 {
		clusterLogin = env.ClusterLoginCmds[0]
	}
	sb.WriteString("# Command run to log into a cluster. %%CLUSTER_ID%% and\n")
	sb.WriteString("# %%INCIDENT_ID%% are substituted at launch.\n")
	fmt.Fprintf(&sb, "cluster_login_command: %s\n", clusterLogin)
	if env != nil && len(env.ClusterLoginCmds) > 1 {
		sb.WriteString("# Also available on this system:\n")
		for _, alt := range env.ClusterLoginCmds[1:] {
			fmt.Fprintf(&sb, "# cluster_login_command: %s\n", alt)
		}
	}
	sb.WriteString("\n")

	for _, entry := range []struct{ key, comment string }{
		{"toolbox_mode", "Fedora Toolbox detection: auto, true, or false."},
		{"chord_prefix", "Prefix key for chord commands."},
		{"rosa_boundary_command", "rosa-boundary cluster login command."},
	} {
		fmt.Fprintf(&sb, "# %s\n%s: %s\n\n", entry.comment, entry.key, DefaultOptionalKeys[entry.key])
	}

	sb.WriteString("# --- Behavior ---\n\n")
	sb.WriteString("# Use emoji markers for flags/agent/watcher (false = text fallbacks).\n")
	sb.WriteString("emoji: true\n\n")
	sb.WriteString("# Escalation level ctrl+e re-escalates to, skipping placeholder tiers.\n")
	sb.WriteString("reescalate_level: 2\n\n")
	sb.WriteString("# Stream :watcher/LLM responses token-by-token when supported.\n")
	sb.WriteString("stream_responses: true\n")

	sb.WriteString("\n# --- Escalation policies (optional — the wizard discovers these) ---\n\n")
	sb.WriteString("# Policy incidents are reassigned to when silenced; use one that routes\n")
	sb.WriteString("# only to bot users, never on-call humans.\n")
	sb.WriteString("# default_silent_escalation_policy: \"PXXXXXX\"\n\n")
	sb.WriteString("# Per-service overrides when a service needs a different silent policy.\n")
	sb.WriteString("# custom_service_escalation_policies:\n")
	sb.WriteString("#   SERVICE_ID: POLICY_ID\n")

	sb.WriteString("\n# --- AI features (optional) ---\n\n")
	if env != nil && env.AgentCLI != "" {
		sb.WriteString("# CLI agent for :agent queries (claude detected on this system).\n")
		fmt.Fprintf(&sb, "agent_cli_command: %s\n\n", env.AgentCLI)
		sb.WriteString("# System prompt for :agent queries — instructs the agent to stay\n")
		sb.WriteString("# read-only and suggest commands for the SRE to review.\n")
		fmt.Fprintf(&sb, "agent_system_prompt: %q\n\n", DefaultOptionalKeys["agent_system_prompt"])
	} else {
		sb.WriteString("# CLI agent for :agent queries. Empty string disables AI features.\n")
		fmt.Fprintf(&sb, "# agent_cli_command: %s\n\n", DefaultOptionalKeys["agent_cli_command"])
		sb.WriteString("# System prompt for :agent queries.\n")
		fmt.Fprintf(&sb, "# agent_system_prompt: %q\n\n", DefaultOptionalKeys["agent_system_prompt"])
	}
	sb.WriteString("# System prompt for the ambient :watcher LLM analysis.\n")
	fmt.Fprintf(&sb, "# watcher_system_prompt: %q\n\n", DefaultOptionalKeys["watcher_system_prompt"])
	sb.WriteString("# LLM API provider for the :watcher (see docs/ai-agents.md).\n")
	sb.WriteString("# llm_api:\n")
	sb.WriteString("#   provider: \"\"\n")
	sb.WriteString("#   api_key_env: \"\"\n")
	sb.WriteString("#   model: \"\"\n")
	sb.WriteString("#   endpoint: \"\"\n")

	sb.WriteString("\n# --- Colors (optional, hex values; see docs/colors.md) ---\n\n")
	sb.WriteString("# colors:\n")
	sb.WriteString("#   text: \"#778da9\"\n")
	sb.WriteString("#   border: \"#415a77\"\n")
	sb.WriteString("#   highlight: \"#ffffff\"\n")
	sb.WriteString("#   selected: \"#415a77\"\n")
	sb.WriteString("#   warning: \"#a4133c\"\n")
	sb.WriteString("#   error: \"#0d1b2a\"\n")
	sb.WriteString("#   muted: \"#5C5C5C\"\n")

	return []byte(sb.String())
}
