package tui

import (
	"testing"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestApprovalsStrip_AddAndCount(t *testing.T) {
	strip := newApprovalsStrip()
	assert.Equal(t, 0, strip.Count())

	strip.Add(Ask{Kind: AskDraftNote, Title: "Draft note"})
	assert.Equal(t, 1, strip.Count())

	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "Run oc get nodes"})
	assert.Equal(t, 2, strip.Count())
}

func TestApprovalsStrip_AcceptInvokesAction(t *testing.T) {
	strip := newApprovalsStrip()
	var called int
	strip.Add(Ask{
		Kind:  AskDraftNote,
		Title: "Post note",
		Action: func() tea.Cmd {
			called++
			return nil
		},
	})

	cmd := strip.Accept(0)
	assert.Nil(t, cmd)
	assert.Equal(t, 1, called, "Action must be invoked exactly once")
	assert.Equal(t, 0, strip.Count(), "Ask must be removed after accept")
}

func TestApprovalsStrip_DismissRemoves(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 1"})
	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "Cmd 1"})

	strip.Dismiss(0)
	assert.Equal(t, 1, strip.Count())
	assert.Equal(t, "Cmd 1", strip.asks[0].Title)
}

func TestApprovalsStrip_AcceptOutOfBounds(t *testing.T) {
	strip := newApprovalsStrip()
	cmd := strip.Accept(0)
	assert.Nil(t, cmd)
	cmd = strip.Accept(-1)
	assert.Nil(t, cmd)
}

func TestApprovalsStrip_DismissOutOfBounds(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Dismiss(0)
	strip.Dismiss(-1)
}

func TestApprovalsStrip_RenderShowsCount(t *testing.T) {
	strip := newApprovalsStrip()
	assert.Equal(t, "", strip.Render(80))

	strip.Add(Ask{Kind: AskDraftNote, Title: "Note"})
	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "Cmd"})

	rendered := strip.Render(80)
	assert.NotEmpty(t, rendered)
	width := lipgloss.Width(rendered)
	require.Greater(t, width, 0, "strip must have non-zero width")
}

func TestApprovalsStrip_RenderEmpty(t *testing.T) {
	strip := newApprovalsStrip()
	assert.Equal(t, "", strip.Render(80))
}

func TestApprovalsStrip_IDAutoGenerated(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note"})
	assert.NotEmpty(t, strip.asks[0].ID)
	assert.Contains(t, strip.asks[0].ID, "ASK-")
}

func TestApprovalsStrip_SelectedBounds(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 1"})
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 2"})
	strip.selected = 1

	strip.Dismiss(1)
	assert.Equal(t, 0, strip.selected, "selected must adjust when item at index removed")
}

func TestApprovalsStrip_RenderShowsActualCount(t *testing.T) {
	strip := newApprovalsStrip()

	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 1"})
	rendered := strip.Render(80)
	assert.Contains(t, rendered, "1 ask")

	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "Cmd 1"})
	rendered = strip.Render(80)
	assert.Contains(t, rendered, "2 asks")

	strip.Add(Ask{Kind: AskEscalationSuggestion, Title: "Escalate"})
	rendered = strip.Render(80)
	assert.Contains(t, rendered, "3 asks")
}

func TestApprovalsStrip_DraftNoteAcceptInvokesPDMock(t *testing.T) {
	strip := newApprovalsStrip()
	var actionCalled bool
	strip.Add(Ask{
		Kind:  AskDraftNote,
		Title: "Add investigation note",
		Body:  "Cluster shows elevated error rate",
		Action: func() tea.Cmd {
			actionCalled = true
			return nil
		},
	})

	cmd := strip.Accept(0)
	assert.Nil(t, cmd)
	assert.True(t, actionCalled, "DraftNote Accept must invoke the Action exactly once")
	assert.Equal(t, 0, strip.Count(), "Ask must be removed after accept")
}

func TestApprovalsStrip_RenderExpandedShowsAsks(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Add(Ask{Kind: AskDraftNote, Title: "Draft note about cluster"})
	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "oc get nodes"})

	rendered := strip.RenderExpanded(80)
	assert.Contains(t, rendered, "Pending Approvals")
	assert.Contains(t, rendered, "[Note]")
	assert.Contains(t, rendered, "[Command]")
	assert.Contains(t, rendered, "Draft note about cluster")
	assert.Contains(t, rendered, "oc get nodes")
	assert.Contains(t, rendered, "Accept")
	assert.Contains(t, rendered, "Dismiss")
}

func TestApprovalsStrip_MoveSelection(t *testing.T) {
	strip := newApprovalsStrip()
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 1"})
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 2"})
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 3"})

	assert.Equal(t, 0, strip.selected)

	strip.MoveDown()
	assert.Equal(t, 1, strip.selected)

	strip.MoveDown()
	assert.Equal(t, 2, strip.selected)

	strip.MoveDown()
	assert.Equal(t, 2, strip.selected, "must not go past the end")

	strip.MoveUp()
	assert.Equal(t, 1, strip.selected)

	strip.MoveUp()
	assert.Equal(t, 0, strip.selected)

	strip.MoveUp()
	assert.Equal(t, 0, strip.selected, "must not go below zero")
}

func TestApprovalsStrip_AcceptSelected(t *testing.T) {
	strip := newApprovalsStrip()
	var called string
	strip.Add(Ask{Kind: AskDraftNote, Title: "Note 1",
		Action: func() tea.Cmd { called = "note1"; return nil }})
	strip.Add(Ask{Kind: AskSuggestedCommand, Title: "Cmd 1",
		Action: func() tea.Cmd { called = "cmd1"; return nil }})

	strip.selected = 1
	strip.Accept(strip.selected)
	assert.Equal(t, "cmd1", called, "must accept the selected ask")
	assert.Equal(t, 1, strip.Count())
}
